build.gradle
=> Upgraded tomcat in response to CVE-2019-0232, CVE-2019-0199

src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
Useful to see the full response if there's an error response in tests.
=> Logging the response in full even when there is an error response.

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
[RIA-3246](https://tools.hmcts.net/jira/browse/RIA-3246)
See Jira. This PR includes the removal of the deprecated installCharts() in Jenkins_CNP and Tomcat version bump.
```
[ ] Yes
[x] No
```
=> RIA-3246 change appeal-type

src/functionalTest/resources/scenarios/RIA-1359-edit-appeal-after-submission-document.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreatorTest.java
https://tools.hmcts.net/jira/browse/RIA-1359
- Updated appeal submission creator to handle `editAppealAfterSubmit` event.
- Added a functional test to check that document is created.
```
[ ] Yes
[x] No
```
=> RIA-1359: Edit appeal after submit event created.

build.gradle
[RIA-3370](https://tools.hmcts.net/jira/browse/RIA-3370)
jackson-core from 2.10.1 to 2.11.1
jackson-datatype-jsr310 from 2.10.1 to 2.11.1
```
[ ] Yes
[x] No
```
=> jackson-core and jackson-datatype-jsr310 from 2.10.1 to 2.11.2

src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocmosisDocumentConversionClientTest.java
N/A
Bug in unit test. Removing assertion comparing an object to itself.
```
[ ] Yes
[x] No
```
=> sonar fix for non-compliant assert in unit test

build.gradle
https://tools.hmcts.net/jira/browse/RIA-3634
addressed CVE (CVE-2020-17527) by updating embed tomcat version
```
[ ] Yes
[X] No
```
=> RIA-3634: addressed CVE (CVE-2020-17527) by updating embed tomcat version

src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-6721
Added isAdmin field to templateFieldValues in appeal submission summary template.
Added isAdmin field to AsylumCaseDefinition.
Updated unit tests.
Testing:
Created and submitted a case with admin. LR, new matters and grounds of appeal hidden as expected.
Created and submitted a case with LR to ensure nothing is affected. Works as expected and shows the LR, new matters and grounds of appeal sections.
Generated submission summary documents during testing attached.
[Case created by Admin.PDF](https://github.com/hmcts/ia-case-documents-api/files/10817119/Case.created.by.Admin.PDF)
[Case created by LR.PDF](https://github.com/hmcts/ia-case-documents-api/files/10817120/Case.created.by.LR.PDF)
**Does this PR introduce a breaking change?** (check one …
=> RIA-6721 Appeal submission summary document for internally created cases

charts/ia-case-documents-api/Chart.yaml, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AdaSuitabilityTemplate.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AdaSuitabilityTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-6844
Added date to ADA suitability document and updated unit tests., No FT changes as underlying data sent to docmosis not part of asylum case data therefore not in the FT HTTP response.
Testing:
E-E test done.
Suitable document:
[DE 50003 2023-ADA-ADA-suitability-decision.PDF](https://github.com/hmcts/ia-case-documents-api/files/11018095/DE.50003.2023-ADA-ADA-suitability-decision.PDF)
Unsuitable document:
[DE 50003 2023-ADA-ADA-suitability-decision-1.PDF](https://github.com/hmcts/ia-case-documents-api/files/11018099/DE.50003.2023-ADA-ADA-suitability-decision-1.PDF)
```
[ ] Yes
[X] No
```
=> Ria 6844 Add date to ADA suitability document

src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-7043
* Added NOTICE_OF_DECISION_UT_TRANSFER enum to DocumentTag.java
```
[ ] Yes
[X] No
```
=> RIA-7043 add NOTICE_OF_DECISION_UT_TRANSFER document tag

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7175-internal-ada-suitability-unsuitable-document.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaSuitabilityReviewUnsuitableLetterGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaSuitabilityReviewUnsuitableLetterGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7175
- New template for DET notification letter document attachment, unsuitable decision
- New generator and configuration bean created
- New document tag (reused from previous PR)
- Added to ignore in bundle order (reused from previous PR)
- Unit and functional tests
```
[ ] Yes
[X] No
```
=> RIA-7175 Internal ADA suitability document - unsuitable

src/functionalTest/resources/scenarios/RIA-7175-internal-ada-suitability-unsuitable-document.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaSuitabilityReviewUnsuitableLetterGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaSuitabilityReviewUnsuitableLetterGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7175
- New template for DET notification letter document attachment, unsuitable decision
- New generator and configuration bean created
- New document tag (reused from previous PR)
- Added to ignore in bundle order (reused from previous PR)
- Unit and functional tests
```
[ ] Yes
[X] No
```
=> RIA-7175 internal ada suitability unsuitable document

src/functionalTest/resources/scenarios/RIA-7172-ho-review-evidence-letter-document.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/HoReviewEvidenceLetterGenerator.java
https://tools.hmcts.net/jira/browse/RIA-7218
- Replaced check for ADA with check for in detention to allow document to generate for both ADA and Detained Non-ADA cases
```
[ ] Yes
[X] No
```
=> RIA-7218 Allow document generation for all detained cases

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-documents-api/Chart.yaml, charts/ia-case-documents-api/values.yaml, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/ConfigValidatorAppListener.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/ConfigValidatorAppListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-7383
Adding ia.config.validator.secret to application.yaml + ConfigValidatorAppListener to check to see if secrets are being applied by azure.
```
[ ] Yes
[x] No
```
=> RIA-7378 - preventing application startup if secrets can't be found

src/functionalTest/resources/scenarios/RIA-7364-internal-ada-decide-an-application-adjourn-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-ada-decide-an-application-expedite-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-ada-decide-an-application-judge-review-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-ada-decide-an-application-transfer-out-of-ada-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-detained-decide-an-application-adjourn-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-detained-decide-an-application-expedite-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-detained-decide-an-application-judge-review-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7364-internal-detained-decide-an-application-transfer-out-of-ada-decision-granted-letter.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/MakeAnApplication.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/MakeAnApplicationTypes.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterHandler.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/MakeAnApplicationService.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/MakeAnApplicationTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/MakeAnApplicationTypesTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/MakeAnApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7364
* Added functionality for decideAnApplication letter generation for internal cases
* Copied across makeAnApplication logic and its parsing/extraction from case data
* Added new doc tag
* Added/updated unit and FTs
```
[ ] Yes
[X] No
```
=> RIA-7364 internal decideAnApplication letter generation

src/functionalTest/resources/scenarios/RIA-7365-internal-ada-decide-an-application-adjourn-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-ada-decide-an-application-expedite-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-ada-decide-an-application-judge-review-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-ada-decide-an-application-transfer-out-of-ada-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-detained-decide-an-application-adjourn-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-detained-decide-an-application-expedite-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-detained-decide-an-application-judge-review-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7365-internal-detained-decide-an-application-transfer-out-of-ada-decision-refused-letter.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDecideAnApplicationLetterHandler.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionRefusedLetterTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDecideAnApplicationLetterHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionRefusedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7365
* Added new template for internal decide an application where decision is refused
* Refactored 7364 so granted+refused use a single handler with independent DocumentCreatorConfiguration beans and seperate templates.
* Added/updated unit/FTs.
```
[ ] Yes
[X] No
```
=> RIA-7365 Internal decide an application decision refused template generation

src/functionalTest/resources/scenarios/RIA-7844-internal-ada-decide-an-application-reinstate-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7844-internal-ada-decide-an-application-reinstate-decision-refused-letter.json, src/functionalTest/resources/scenarios/RIA-7844-internal-detained-decide-an-application-reinstate-decision-granted-letter.json, src/functionalTest/resources/scenarios/RIA-7844-internal-detained-decide-an-application-reinstate-decision-refused-letter.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplate.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7844
* Added content for application type - reinstate to InternalDecideAnApplicationDecisionGrantedLetterTemplate.getWhatHappensNextContent()
* Added reinstate content test
* Added FTs for reinstate application type when decided
```
[ ] Yes
[X] No
```
=> RIA-7844 reinstate content added to InternalDecideAnApplicationDecisionGrantedLetterTemplate

src/functionalTest/resources/scenarios/RIA-7322-internal-hearing-requirements-updated-ada-letter.json, src/functionalTest/resources/scenarios/RIA-7322-internal-hearing-requirements-updated-non-ada-letter.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHearingRequirementsUpdatedLetterTemplate.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHearingRequirementsUpdatedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7322
- hearingDate no longer a field in template. Removed these values from personalisation, unit tests and functional tests
```
[ ] Yes
[X] No
```
=> RIA-7322 hearingDate removed from template

src/functionalTest/resources/scenarios/RIA-7370-internal-ada-home-office-upload-addendum-evidence.json, src/functionalTest/resources/scenarios/RIA-7370-internal-ada-home-office-upload-additional-evidence.json, src/functionalTest/resources/scenarios/RIA-7370-internal-ada-legal-officer-upload-addendum-evidence-supplied-by-ho.json, src/functionalTest/resources/scenarios/RIA-7370-internal-detained-home-office-upload-addendum-evidence.json, src/functionalTest/resources/scenarios/RIA-7370-internal-detained-home-office-upload-additional-evidence.json, src/functionalTest/resources/scenarios/RIA-7370-internal-detained-legal-officer-upload-addendum-evidence-supplied-by-ho.json, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentWithMetadata.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/HasDocument.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUploadAdditionalEvidenceGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHomeOfficeUploadAdditionalAndAddendumEvidenceTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalLegalOfficerUploadAdditionalAndAddendumEvidenceTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentWithMetadataTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUploadAdditionalEvidenceGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHomeOfficeUploadAdditionalAndAddendumEvidenceTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalLegalOfficerUploadAdditionalAndAddendumEvidenceTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-7370
* Refactored implementation of RIA-7427 to make InternalUploadAdditionalEvidenceGenerator generic for all users
* Imported HasDocument interface and made current implementation of DocumentWithMetadata implement it
* Imported events from case-api
* Added 2 new doc tags (LO additional evidence upload and HO additional evidence upload)
* Created 2 new templates for HO and LO additional evidence upload
* Added new methods in AsylumCaseUtils to extract addendum evidence documents and to fetch most recent addendum evidence added
* Created 2 new beans in DocumentCreatorConfiguration (LO/HO additional evidence upload)
* 2 new application.yaml entries for document templates
* Updated existing tests and added new unit/FTs
=> RIA-7370 HO upload additional/addendum evidence + LO upload addendum evidence doc generation

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapper.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapperTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/CmaAppointmentNoticeTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7195
- use isIntegrated field to determine this hearing whether is list assist hearing or not
- if isIntegrated set to true, it will be "list assist hearing" and the hearing notice document will display without listing reference number
- if isIntegrated set to false, it will be "aria hearing" and the hearing notice document will display listing reference number
- temporary suppress the CVE problem
=> RIA-7195 remove listing reference number from notification template when hearing list assist hearing v2

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/InterpreterLanguageCategory.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8119
- Applicant and FCS interpreter requirements added to the bail application document upon submission
- Unit tests added to cover spoken+sign languages, language ref data + manual entry, and applicant+fcs interpreter requirements.
=> RIA-8119 Bail application document changes with added interpreter fields

build.gradle
[VUL-5809](https://tools.hmcts.net/jira/browse/VUL-5809)
- Upgraded serenity to 4.1.3
- Upgraded restAssured to 5.4.0
- Removed unused reference to springHystrix
=> RIA-TASK VUL-5809 Upgrade serenity, restAssured, remove springHystrix reference

src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingTemplate.java, src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/model/refdata/CourtVenue.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingInitialListingTemplateTest.java, src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingRelistingTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8802
- display the listing location from ref data instead of using CCD address
- update unit test
=> RIA-8802 bails notice of hearing displays the correct location information

charts/ia-case-documents-api/Chart.yaml
Bump charts version
Some of the template versions/names were straightened out in the 5.2.1 release. We're hoping this will help fix https://tools.hmcts.net/jira/browse/DIAC-401
=> DIAC-401 Update chart version
