- src/functionalTest/resources/templates/minimal-appeal-submitted.json
legalRepresentativeName updated to "A Legal Rep" as per AAT test user data
> updated test data: legalRepresentativeName changed to be in line with AAT

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDO-3629
Configure PROD DNS as per DevOps request
```
[ ] Yes
[X] No
```
> PROD DNS server for Docmosis name resolution

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/MapFieldAssertor.java
https://tools.hmcts.net/jira/browse/RIA-842
Send the hearing requirements direction to legal rep.
```
[ ] Yes
[X] No
```
> RIA-842 Send legal rep hearing requirements direction

- config/owasp/suppressions.xml
Adding suppression for CVE-2019-3795
```
[ ] Yes
[X] No
```
> Adding suppression for CVE-2019-3795

- build.gradle
- src/functionalTest/resources/scenarios/RIA-1152-&-1153- generate-decisions-and-reasons.json
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/AsylumCaseFixtures.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/CallbackBuilder.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/CaseDetailsBuilder.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/DocmosisStub.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/IaApiClient.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/StubbedIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DecisionAndReasonsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DecisionAndReasonsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/enties/em/BundleTest.java
> Ria 1152 & 1153 generate decision and reasons

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/PreSubmitCallbackDispatcher.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/PreSubmitCallbackDispatcherTest.java
[RIA-1539](https://tools.hmcts.net/jira/browse/RIA-1539)
pre-submit dispatcher handlers ordering for being consistent with ia-case-api:
https://github.com/hmcts/ia-case-api/pull/104
```
[ ] Yes
[x] No
```
> RIA-1539 pre-submit dispatcher handlers sorting

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingBundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingBundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/PreSubmitCallbackDispatcherTest.java
[RIA-1514](https://tools.hmcts.net/jira/browse/RIA-1514)
branch created from RIA-1152-&-1153 (needs rebase before code review and merge to master) 
hearing pdf bundle ordering
```
[ ] Yes
[x] No
```
> RIA-1514 hearing bundle order

- Jenkinsfile_CNP
- build.gradle
[RIA-1640](https://tools.hmcts.net/jira/browse/RIA-1640)
exclude tests + fix vulnerabilities
```
[ ] Yes
[x] No
```
> RIA-1640 exclude tests + fix security vulnerabilities

- build.gradle
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestrator.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/PreSubmitCallbackDispatcherTest.java
[RIA-481](https://tools.hmcts.net/jira/browse/RIA-481)
skeleton bundle + handlers refactoring + snakeyaml issue
```
[ ] Yes
[x] No
```
> Ria 481 skeleton bundle

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-412-&-1571-hearing-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplate.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplateTest.java
[RIA-1571](https://tools.hmcts.net/jira/browse/RIA-1571)
aria reference in hearing notice pdf
```
[ ] Yes
[x] No
```
> RIA-1571 list case by admin - aria reference

- Jenkinsfile_CNP
[RIA-1571](https://tools.hmcts.net/jira/browse/RIA-1571)
enable charts and jenkins configuration
```
[ ] Yes
[x] No
```
> RIA-1571 enable charts and adding admin user variables

- src/functionalTest/resources/scenarios/RIA-362-edit-case-listing-hearing-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentHandlerTest.java
RIA-362: editing a case listing
RIA-362: Added functional test
RIA-362: Added functional test
```
[ ] Yes
[ ] No
```
> RIA-362: editing a case listing

- charts/ia-case-documents-api/values.yaml
https://tools.hmcts.net/jira/browse/RIA-1653
```
[ ] Yes
[x] No
```
> RIA-1653 updating docker image

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- build.gradle
Refactoring Jenkins secret code.
```
[ ] Yes
[ ] No
```
> removing deprecated jenkins code

- Jenkinsfile_CNP
- charts/ia-case-documents-api/values.aat.template.yaml
- charts/ia-case-documents-api/values.yaml
aat staging aks
```
[ ] Yes
[ ] No
```
> aat staging aks

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-362-&-1673-edit-case-listing-hearing-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/Application.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DocumentTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplateTest.java
[RIA-1673](https://tools.hmcts.net/jira/browse/RIA-1673)
See Jira
```
[ ] Yes
[x] No
```
> Ria 1673 edited hearing notice

- build.gradle
- src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-hearing-notice-document-bradford-hearing-centre.json
- src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-hearing-notice-document-newport-hearing-centre.json
- src/functionalTest/resources/scenarios/RIA-1380-hearing-notice-document-bradford-hearing-centre.json
- src/functionalTest/resources/scenarios/RIA-1380-hearing-notice-document-newport-hearing-centre.json
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplate.java
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplateTest.java
[RIA-1380](https://tools.hmcts.net/jira/browse/RIA-1380)
See Jira
```
[ ] Yes
[x] No
```
> Ria 1380 add hearing centres

- src/main/resources/application.yaml
[RIA-1654](https://tools.hmcts.net/jira/browse/RIA-1654)
admin edit listing
```
[ ] Yes
[x] No
```
> Ria 1654 admin edit case

- build.gradle
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCase.java
N/A
security vulnerabilities fix (CVE-2019-14540, CVE-2019-16335)
```
[ ] Yes
[x] No
```
> fix security vulnerabilities within jackson-databind

- zap-known-issues.xml
[RIA-1643](https://tools.hmcts.net/jira/browse/RIA-1643)
zap alerts
please refer to the comment in PR https://github.com/hmcts/ia-case-api/pull/139
```
[ ] Yes
[ ] No
```
> zap ignore known alerts

- Dockerfile
- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/requirements.yaml
Upgrading chart and docker base image
> Upgrading java chart and docker base image.

- Dockerfile
- build.gradle
- web.config
N/A
security vulnerabilities fix
```
[ ] Yes
[x] No
```
> security vulnerabilities fix

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGenerator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGeneratorTest.java
[RIA-1846](https://tools.hmcts.net/jira/browse/RIA-1846)
additional evidence bundle
```
[ ] Yes
[x] No
```
> RIA-1846 additional evidence bundle

- Jenkinsfile_CNP
> Disable AKS go live

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
N/A
add missing DocumentTag values
```
[ ] Yes
[x] No
```
> add missing DocumentTag values

- Jenkinsfile_CNP
N/A
aks go live in PROD
```
[ ] Yes
[x] No
```
> aks go live in PROD

- security.sh
N/A
zap encoding
```
[ ] Yes
[x] No
```
> zap encoding for Python 2/3

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
N/A
empty line to re-trigger build
```
[ ] Yes
[x] No
```
> empty line to re-trigger full build

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/GenerateDecisionAndReasonsTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/DocumentCaseApiVerifications.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/GivensBuilder.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/IaCaseDocumentsApiClient.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/SpringBootIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/AsylumCaseForTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/Builder.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/CallbackForTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/CaseDetailsForTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/PreSubmitCallbackResponseForTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/fixtures/UserDetailsForTest.java
- src/integrationTest/resources/application-integration.yaml
- src/main/resources/application.yaml
Integration test refactor: imported test infrastructure
```
[ ] Yes
[ ] No
```
> Integration test refactor: imported test infrastructure

- Jenkinsfile_nightly
N/A
change url env variable for tests
```
[ ] Yes
[x] No
```
> change url for nightly build tests

- audit.json
- security.sh
N/A
false positives for zap-glue
```
[ ] Yes
[x] No
```
> false positives for zap-glue

- src/functionalTest/resources/templates/minimal-appeal-started.json
- src/functionalTest/resources/templates/minimal-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
[RIA-1000](https://tools.hmcts.net/jira/browse/RIA-1000)
New fields added to appeal submission
```
[ ] Yes
[x] No
```
> RIA-1000 New fields added to appeal submission

- src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-hearing-notice-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-hearing-notice-iac-glasgow.json
- src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-hearing-notice-iac-hatton-cross.json
- src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-hearing-notice-iac-north-shields.json
- src/functionalTest/resources/scenarios/RIA-1976-hearing-notice-document-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-1976-hearing-notice-document-iac-glasgow.json
- src/functionalTest/resources/scenarios/RIA-1976-hearing-notice-document-iac-hatton-cross.json
- src/functionalTest/resources/scenarios/RIA-1976-hearing-notice-document-iac-north-shields.json
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplateTest.java
[RIA-1976](https://tools.hmcts.net/jira/browse/RIA-1976)
See Jira
```
[ ] Yes
[x] No
```
> RIA-1976 add new hearing centres

- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document.json
- src/functionalTest/resources/scenarios/RIA-941-hearing-bundle.json
N/A
enable stitching tests
```
[ ] Yes
[x] No
```
> enable stitching tests

- build.gradle
- infrastructure/ithc.tfvars
N/A
AKS migration for ITHC env
```
[ ] Yes
[x] No
```
> AKS migration for ITHC env

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-2011
Changes to remove the requirements capture page from listing flow and populate the requirements reviewed by case officer
```
[ ] Yes
[X] No
```
> Ria 2011 modify admin listing

- infrastructure/main.tf
N/A
ithc docmosis config
```
[ ] Yes
[x] No
```
> ithc docmosis config

- build.gradle
N/A
remove deprecated properties
```
[ ] Yes
[x] No
```
> remove deprecated properties

- build.gradle
N/A
fix sonar build
```
[ ] Yes
[x] No
```
> fix sonar build

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/WelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/BundleRequestExecutor.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/WelcomeController.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/BundleRequestExecutorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocmosisDocumentConversionClientTest.java
N/A
fix security vulnerabilities
```
[ ] Yes
[x] No
```
> fix security vulnerabilities

- Jenkinsfile_CNP
- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- infrastructure/main.tf
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-disable-stitching.json
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-enable-stitching.json
- src/functionalTest/resources/scenarios/RIA-941-hearing-bundle-disable-stitching.json
- src/functionalTest/resources/scenarios/RIA-941-hearing-bundle-enable-stithing.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGenerator.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/PreSubmitCallbackDispatcherTest.java
[RIA-2378](https://tools.hmcts.net/jira/browse/RIA-2378)
RIA-2378 em-stitching-flag in documents-api
```
[ ] Yes
[x] No
```
> RIA-2378 em-stitching-flag in documents-api

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-2537-appeal-submission-document-citizen-role.json
- src/main/resources/application.yaml
Adds permissions for the citizen role to use the service.
```
[ ] Yes
[ x] No
```
> Citizen Permission

- build.gradle
- config/checkstyle/checkstyle.xml
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/Direction.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/DatesToAvoid.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/DatesToAvoidTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
N/A
fix security vulnerability in checkstyle plugin
```
[ ] Yes
[x] No
```
> fix security vulnerability in checkstyle plugin

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
> removing aadidentityname config

- security.sh
N/A
zap testing report in HTML
```
[ ] Yes
[x] No
```
> zap testing report in HTML

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.preview.template.yaml
N/A
remove deprecation in config
```
[ ] Yes
[x] No
```
> remove deprecation in config

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingRequirementsCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingRequirementsCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
[RIA-2031](https://tools.hmcts.net/jira/browse/RIA-2031)
update hearing requirements
```
[ ] Yes
[x] No
```
> RIA-2031 update hearing requirements

- src/main/resources/application.yaml
[RIA-2337](https://tools.hmcts.net/jira/browse/RIA-2337)
See Jira
```
[ ] Yes
[x] No
```
> RIA-2337 template name change

- src/functionalTest/resources/scenarios/RIA-2521-edit-case-listing-hearing-notice-changed-hearing-centre.json
- src/functionalTest/resources/scenarios/RIA-2521-edit-case-listing-hearing-notice-changed-hearing-date.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedDetailsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedRequirementsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProvider.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedDetailsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedRequirementsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProviderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinderTest.java
[RIA-2521](https://tools.hmcts.net/jira/browse/RIA-2521)
See Jira
```
[ ] Yes
[x] No
```
> RIA-2521 update hearing requirements hearing notice

- build.gradle
dependency check fix for CVE-2020-1938
```
[ ] Yes
[X] No
```
> dependency check fix for CVE-2020-1938

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-1280-generate-decisions-and-reasons-judge.json
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-1280
Prepare Decision and Reasons document by Judge
```
[ ] Yes
[X] No
```
>  RIA-1280: prepare Decision and Reasons document by Judge

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-2239-end-appeal-notice-document.json
- src/main/resources/application.yaml
[RIA-2239](https://tools.hmcts.net/jira/browse/RIA-2239)
Functionality added to allow a judge to end appeal
```
[ ] Yes
[X] No
```
> RIA-2239 judge endAppeal

- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-1939-send-decisions-and-reasons-admin.json
- src/functionalTest/resources/scenarios/RIA-1939-send-decisions-and-reasons-judge.json
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-1939
Upload and send Decision and Reasons document (FT Judge)
```
[ ] Yes
[X] No
```
> Ria 1939 judge upload decision

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
https://tools.hmcts.net/jira/browse/RIA-2765
Added CCD_URL env value
```
[ ] Yes
[ X] No
```
> Added CCD_URL env value

- src/smokeTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/SmokeTest.java
[RIA-1906](https://tools.hmcts.net/jira/browse/RIA-2196)
Smoke test improvement
```
[ ] Yes
[x] No
```
> RIA-1906 health smoke test

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/AsylumCaseRequestAdapter.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/CallbackControllerAdvice.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/CallbackControllerAdviceTest.java
[RIA-2646](https://tools.hmcts.net/jira/browse/RIA-2646)
Log ccd case id in exceptions
```
[ ] Yes
[x] No
```
> RIA-2646 log ccd case id on exceptions

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RIA-2765
RIA-2765 ccd-url out_of_vault
```
[ ] Yes
[ X] No
```
> secret ccd-url out of vault

- infrastructure/main.tf
N/A
Docmosis key cleanup
```
[ ] Yes
[x] No
```
> Docmosis key cleanup

- infrastructure/output.tf
N/A
fix Terraform script
```
[ ] Yes
[x] No
```
> fix Terraform script

- infrastructure/perftest.tfvars
RIA-2418
missing dns group for perftest
```
[ ] Yes
[x] No
```
> missing dns group for perftest

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RIA-2765
RIA-2765 Removed urls out of vault
```
[ ] Yes
[ X] No
```
> Removed urls out of vault

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- build.gradle
- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/FeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/LaunchDarklyFeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/FeatureToggleConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java
N/A
Launch Darkly integration
```
[ ] Yes
[x] No
```
> Launch Darkly integration

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- infrastructure/main.tf
- src/functionalTest/resources/templates/minimal-appeal-started.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ContactPreference.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumAppealTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ContactPreferenceTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
[RIA-2693](https://tools.hmcts.net/jira/browse/RIA-2693)
Added email and mobile number support to appeal submission template
```
[ ] Yes
[x] No
```
> RIA-2693 email or mobile to the appeal submission template

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ClarifyingQuestion.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/Direction.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ClarifyingQuestionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTest.java
Added new domeain objects for clarifying questions.
```
[ ] Yes
[ ] No
```
> RIA-2864-Clarifying_question

- build.gradle
- config/owasp/suppressions.xml
- docker-compose.yml
- src/contractTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/EvidenceManagementBundlingTest.java
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-3035
Change description
RIA-3035 Bundling-PACT
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No
> Contract Test EM

- config/owasp/suppressions.xml
- src/main/resources/strings.tsv
[RIA-3246](https://tools.hmcts.net/jira/browse/RIA-3246)
```
[ ] Yes
[ ] No
```
> RIA-3246 change appeal-type

- Jenkinsfile_nightly
- security.sh
[RIA-3171](https://tools.hmcts.net/jira/browse/RIA-3171)
See Jira
```
[ ] Yes
[x] No
```
> RIA-3171 nightly build fix

- src/functionalTest/resources/scenarios/RIA-1976-RIA-2804-hearing-notice-document-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-2970-hearing-adjourned-notice-document-iac.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeOfAdjournmentWithoutADate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/HearingNoticeTemplateConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeOfAdjournmentWithoutADateTest.java
* add new template for when hearing is adjourned with no date
* add unit test
* add functional test
* fix check style issues
* rename functional test
* add back the 1976 birmingham scenario
* fix functional test
* update template filename with the one from Sharepoint
```
[ ] Yes
[ ] No
```
> Adjourned without a date epic

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-stitching-save-and-return-disabled.json
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-stitching-save-and-return-enabled.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGenerator.java
- src/main/resources/application-local.yaml
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGeneratorTest.java
https://tools.hmcts.net/jira/browse/RIA-2918
> RIA-2918 add save and continue feature flag

- infrastructure/main.tf
- src/functionalTest/resources/scenarios/RIA-3048-cma-requirements-request-document.json
- src/functionalTest/resources/templates/minimal-aip-appeal-submitted.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CmaRequirementsCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/AppointmentRequirementsFieldMapper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/CmaRequirementsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-3048
Added Docmosis Template configuration for aip cma requirements.
Abstracted shared appointment personalisation.
Updated tests.
```
[ ] Yes
[ x] No
```
> RIA-3048: CMA Requirements

- audit.json
https://tools.hmcts.net/jira/browse/RIA-3420
RIA-3420_Nighly_Build_fix
```
[ ] Yes
[X] No
```
> RIA-3420_Nighly_Build

- lombok.config
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentWithMetadata.java
https://tools.hmcts.net/jira/browse/RIA-2830
> RIA-2830 update the entity type

- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/AsylumCaseFixtures.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentWithMetadata.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentReceiver.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentWithMetadataTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSkeletonBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingBundleGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DocumentHandlerTest.java
[RIA-3411](https://tools.hmcts.net/jira/browse/RIA-3411)
```
[x] Yes
[ ] No
```
> RIA-3411 fix end an appeal

- .travis.yml
- Dockerfile
- build.gradle
[RIA-3444](https://tools.hmcts.net/jira/browse/RIA-3444)
```
[x] Yes
[ ] No
```
> RIA-3444 upgrading to Java11

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
[RIA-2951](https://tools.hmcts.net/jira/browse/RIA-2951)
Gradle version bumped to v6.5
```
[ ] Yes
[x] No
```
> RIA-2951 gradle version bumped to v6.5

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-3372
CVE suppression cleanup
```
[ ] Yes
[X] No
```
> RIA-3372: CVE checks clean up

- infrastructure/state.tf
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/EndpointSecurityTest.java
N/A
remove deprecated terraform script
```
[ ] Yes
[x] No
```
> remove deprecated terraform script

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/security/RequestUserAccessTokenProvider.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreatorTest.java
[RIA-3412](https://tools.hmcts.net/jira/browse/RIA-3412)
Pay and submit appeal journey
```
[ ] Yes
[x] No
```
> RIA-3412 pay and submit appeal

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/security/idam/IdamAuthorizor.java
N/A
fix second Sonar issue
```
[ ] Yes
[x] No
```
> fix second Sonar issue

- src/main/resources/application.yaml
[RIA-3170](https://tools.hmcts.net/jira/browse/RIA-3170)
Edit hearing notice template text appearing in the index page of the hearing notice
```
[ ] Yes
[x] No
```
> RIA-3170 edit listing template text fix for hearing notice

- src/main/resources/application.yaml
N/A
Rollback for missing template TB-IAC-HNO-ENG-00244.docx
```
[ ] Yes
[x] No
```
> RIA-3170 rollback to previous template

- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinder.java
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-2323
Added new hearing centres:
- Glasgow tribunal centre
- Coventry
- Newcastle
```
[ ] Yes
[x ] No
```
> RIA-2323: Adding new hearing centres

- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/RIA-2010
Add stateless
```
[ ] Yes
[x] No
```
> Ria 2010 add stateless

- src/functionalTest/resources/scenarios/RIA-3434-appeal-submission-document_after_pay_and_submit_failed_changed_to_pay_later.json
- src/functionalTest/resources/scenarios/RIA-3434-appeal-submission-document_after_pay_and_submit_failed_changed_to_pay_offline.json
- src/functionalTest/resources/scenarios/RIA-3434-appeal-submission-document_after_pay_and_submit_paid.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatus.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatusTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreatorTest.java
[RIA-3434](https://tools.hmcts.net/jira/browse/RIA-3434)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3434 pay offline by card pa

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/perftest.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/LivenessProbeTest.java
N/A
cleanup terraform
```
[ ] Yes
[x] No
```
> cleanup terraform

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatus.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatusTest.java
[RIA-3473](https://tools.hmcts.net/jira/browse/RIA-3473)
Mark appeal as paid for the appeal types EA/HU/PA
```
[ ] Yes
[x] No
```
> RIA-3473 mark appeal as paid of appeal types EA/HU/PA

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatus.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatusTest.java
https://tools.hmcts.net/jira/browse/RIA-3592
RIA-3592_payment_status
```
[ ] Yes
[X] No
```
> Ria 3592 payment status

- infrastructure/main.tf
RIA-3668
Azure provider v2
```
[ ] Yes
[x] No
```
> RIA-3668 Azure provider v2

- src/main/resources/application.yaml
[RIA-3457](https://tools.hmcts.net/jira/browse/RIA-3457)
CaseOfficer and Judge decide an online application
```
[ ] Yes
[x] No
```
> RIA-3451 CO and Judge decide an application

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTag.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTagTest.java
[RIA-3652](https://tools.hmcts.net/jira/browse/RIA-3652)
See Jira
```
[ ] Yes
[x] No
```
> RIA-3652 direction and state change for ftpa decision reheard

- build.gradle
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/FileTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/CmaRequirementsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/AsylumCaseRequestAdapterTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/CallbackControllerAdviceTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/enties/em/BundleCaseDataTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/enties/em/BundleDocumentTest.java
[RIA-3760](https://tools.hmcts.net/jira/browse/RIA-3760)
```
[ ] Yes
[x] No
```
> RIA-3760 Solving mutations after junit5 migration

- src/functionalTest/resources/scenarios/RIA-3683-edit-case-listing-hearing-notice-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-3683-hearing-notice-document-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-3683-reheard-edit-case-listing-hearing-notice-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-3683-reheard-hearing-notice-document-iac-birmingham.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
[RIA-3683](https://tools.hmcts.net/jira/browse/RIA-3683)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3683 ao lists reheard case

- src/functionalTest/resources/scenarios/RIA-3131-generate-decisions-and-reasons.json
- src/functionalTest/resources/scenarios/RIA-3131-generate-reheard-decisions-and-reasons.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestrator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/DecisionAndReasonsCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestratorTest.java
[RIA-3131](https://tools.hmcts.net/jira/browse/RIA-3131)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3131 pre hearing to decision

- src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-send-decisions-and-reasons.json
- src/functionalTest/resources/scenarios/RIA-3132-send-decisions-and-reasons.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestrator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestratorTest.java
[RIA-3132](https://tools.hmcts.net/jira/browse/RIA-3132)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3132 decision to decided

- build.gradle
https://tools.hmcts.net/jira/browse/RIA-3670
updated dependabot depdendcies (changes from  PRs 271, 272, 301, 310, 320, 328)
```
[ ] Yes
[X] No
```
> RIA-3670: updated dependabot depdendcies (changes from  PRs 271, 272, 301, 310, 320, 328)

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AppealDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CmaAppointmentNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CmaRequirementsCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/health/DownStreamHealthIndicatorTest.java
RIA-3885:Fix mutation test, add suppression for CVE-2020-8908
https://tools.hmcts.net/jira/browse/RIA-3885
```
[ ] Yes
[x ] No
```
> RIA-3885:Fix mutation test, add suppression for CVE-2020-8908

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundlePreparer.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/CheckValuesTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundlePreparerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsPdfServiceTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/WordDocumentToPdfConverterTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DecisionAndReasonsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeEditedTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedDetailsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedRequirementsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProviderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/AsylumCaseRequestAdapterTest.java
RIA-3885:Mutation threshold coverage, Add suppression for lang-tag
https://tools.hmcts.net/jira/browse/RIA-3885
```
[ ] Yes
[ x] No
```
> RIA-3885:Mutation threshold coverage, Add suppression for lang-tag

- build.gradle
- config/owasp/suppressions.xml
- src/main/resources/META-INF/additional-spring-configuration-metadata.json
- src/main/resources/application.yaml
[RIA-3775](https://tools.hmcts.net/jira/browse/RIA-3775)
```
[ ] Yes
[x] No
```
> RIA-3775 upgrade Spring boot to version 2.3.3.RELEASE

- charts/ia-case-documents-api/Chart.yaml
[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```
> RIA-3710 Migrate to Helm charts v2

- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/TsvStringProviderTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinder.java
- src/main/resources/strings.tsv
[RIA-3810](https://tools.hmcts.net/jira/browse/RIA-3810)
Belfast hearing centre added
```
[ ] Yes
[x] No
```
> RIA-3810 Belfast hearing centre added

- .github/workflows/swagger.yml
- build.gradle
- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- config/owasp/suppressions.xml
[RIA-4086](https://tools.hmcts.net/jira/browse/RIA-4086)
Update all the non-prod docmosis urls
```
[ ] Yes
[x] No
```
> RIA-4086 Updated docmosis non-prod urls

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/LaunchDarklyFeatureToggler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/FeatureToggleConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java
[RIA-4054](https://tools.hmcts.net/jira/browse/RIA-4054)
```
[ ] Yes
[x] No
```
> RIA-4054 Upgrade launchdarkly version from 4.14.1 to 5.2.2

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/SpringBootIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/Application.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/PreSubmitCallbackController.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/WelcomeController.java
[RIA-4070](https://tools.hmcts.net/jira/browse/RIA-4070)
```
[ ] Yes
[x] No
```
> RIA-4070 Upgrade guava version 30.0

- src/main/resources/application.yaml
N/A
Changes are needed to differentiate remote and local Docmosis service
```
[ ] Yes
[x] No
```
> Tornado integration

- src/functionalTest/resources/scenarios/RIA-3863-appeal-submission-document-ooc.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionType.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-3863
RIA-3863 - template changes for ooc submission
```
[ ] Yes
[X] No
```
> RIA-3863_ooc_pdf

- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-hearing-centre-to-remote-reheard.json
- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-hearing-centre-to-remote.json
- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-remote-hearing-reheard.json
- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-remote-hearing.json
- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-remote-to-hearing-centre-reheard.json
- src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-hearing-notice-remote-to-hearing-centre.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedDetailsRemoteTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProvider.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeEditedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedDetailsRemoteTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProviderTest.java
[RIA-3722](https://tools.hmcts.net/jira/browse/RIA-3722)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3722 edit listing

- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-judge-reheard.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-judge.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-tcw-reheard.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-tcw.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/AppointmentRequirementsFieldMapper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
[RIA-3721](https://tools.hmcts.net/jira/browse/RIA-3721)
See Jira
```
[ ] Yes
[x] No
```
> Ria 3721 update hearing requirements

- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-in-country-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-in-country.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-ooc-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-ooc.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-in-country-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-in-country.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-ooc-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-ooc.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
[RIA-3825](https://tools.hmcts.net/jira/browse/RIA-3825)
See Jira
```
[ ] Yes
[x] No
```
> RIA-3825 ooc hearing requirements

- build.gradle
- charts/ia-case-documents-api/Chart.yaml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/WordDocumentToPdfConverter.java
[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
fix cve and upgrade Charts
```
[ ] Yes
[x] No
```
> RIA-4278 fix CVE and upgrade Charts

- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AppealDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumAppealTypeTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ContactPreferenceTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingLengthTest.java
N/A
Additional pitest coverage to for nightly build.
```
[ ] Yes
[x] No
```
> additional pitests for nightly build

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
[RIA-4047](https://tools.hmcts.net/jira/browse/RIA-4047)
Record out of time decision documentTag
```
[ ] Yes
[x] No
```
> RIA-4047 Record out of time decision documentTag added

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocmosisDocumentGenerator.java
N/A
additional logging
```
[ ] Yes
[n] No
```
> additional logging

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandler.java
[RIA-4251](https://tools.hmcts.net/jira/browse/RIA-4251)
```
[ ] Yes
[x] No
```
> RIA-4251 Customise hearing bundle event doesn't generate all documents

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandler.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/CustomiseHearingBundleHandlerTest.java
[RIA-3887](https://tools.hmcts.net/jira/browse/)
```
[ ] Yes
[x] No
```
> RIA-3887 ia-documents-api refactoring

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
- src/functionalTest/resources/scenarios/RIA-4324-end-appeal-appellant-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/JourneyType.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/EndAppealAppellantTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/EndAppealTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/EndAppealTemplateHelper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/EmailAddressFinder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/HearingCentreEmailAddressesConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/EndAppealAppellantTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/EndAppealTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/EndAppealTemplateHelperTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/EmailAddressFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-4324
Notice of ended appeal document for Appellant appeals
```
[ ] Yes
[X] No
```
> RIA-4324: Notice of ended appeal document for Appellant appeals

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/main/resources/strings.tsv
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
[RIA-4473](https://tools.hmcts.net/jira/browse/RIA-4473)
```
[ ] Yes
[x] No
```
> RIA-4473 Decision without hearing route

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionType.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionTypeTest.java
[RIA-4372](https://tools.hmcts.net/jira/browse/RIA-4372)
```
[ ] Yes
[x] No
```
> RIA-4372 Add Home Office decision type into OOC flow

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
[RIA-4262](https://tools.hmcts.net/jira/browse/RIA-4262)
AIP PerfTest env
```
[ ] Yes
[x] No
```
> RIA-4262 AIP move to the gov.uk subdomain

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java
N/A
reset Jenkins pipeline
```
[ ] Yes
[x] No
```
> reset Jenkins pipeline

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
N/A
add quotes to the configuration file
```
[ ] Yes
[x] No
```
> add quotes to the configuration file

- build.gradle
- charts/ia-case-documents-api/Chart.yaml
N/A
update charts to 3.6.0
```
[ ] Yes
[x] No
```
> update charts to 3.6.0

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
N/A
Ingress host in values.yaml
```
[ ] Yes
[x] No
```
> Ingress host in values.yaml

- src/functionalTest/resources/scenarios/RIA-4351-generate-upper-tribunal-bundle-stitching-enabled.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpperTribunalBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpperTribunalBundleHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
[RIA-4351](https://tools.hmcts.net/jira/browse/RIA-4351)
See Jira
```
[ ] Yes
[x] No
```
> RIA-4351 generate upper tribunal bundle

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-4691
editAppealAfterSubmit role-event access added for citizen
```
[ ] Yes
[X] No
```
> RIA-4691: editAppealAfterSubmit role-event access added for citizen

- src/main/resources/application.yaml
RIA-4863
allow draftHearingRequirements event for citizen role
> RIA-4863: allow draftHearingRequirements event for citizen role

- src/functionalTest/resources/scenarios/RIA-4925-appeal-reasons-with-no-evidence-document.json
- src/functionalTest/resources/scenarios/RIA-4928-clarifying-questions-answers-document.json
- src/functionalTest/resources/scenarios/RIA-4936-send-decisions-and-reasons.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsCoverLetterService.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppellantDecisionAndReasonsCoverLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsCoverLetterServiceTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppellantDecisionAndReasonsCoverLetterTemplateTest.java
###Decision and Reason Cover Letter ###
```
[ ] Yes
[x ] No
```
> RIA-4936 Decision: Decision and Reason Cover letter

- src/functionalTest/resources/scenarios/RIA-4926-generate-hearing-ready-bundle-stitching-enabled-aip.json
[RIA-4926](https://tools.hmcts.net/jira/browse/RIA-4926)
See Jira
```
[ ] Yes
[x] No
```
> Ria 4926 bundling template update

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/Direction.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DirectionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/ClarifyingQuestionsAnswersTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-4540
Added uniqueId and directionType to Direction class
```
[ ] Yes
[X] No
```
> RIA-4540: Added uniqueId and directionType to Direction class

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ClarifyingQuestionAnswer.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ClarifyingQuestionAnswerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/ClarifyingQuestionsAnswersTemplateTest.java
[RIA-4593](https://tools.hmcts.net/jira/browse/RIA-4593)
See Jira
```
[ ] Yes
[x] No
```
> RIA-4593 multiple clarifying questions

- charts/ia-case-documents-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```
> RIA-5503: Upgrade base helm charts to latest

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandler.java
- src/main/resources/application.yaml
[RIA-4600](https://tools.hmcts.net/jira/browse/RIA-4600)
```
[ ] Yes
[x] No
```
> RIA-4600 Update decision and reasons cover letter

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-granted.json
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-judge-minded-refusal.json
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-refusal.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedGrantedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedMindedRefusalCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedRefusalCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BailDocumentHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailDecisionUnsignedGrantedTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailDecisionUnsignedMindedRefusalTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailDecisionUnsignedRefusalTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/helper/BailDecisionUnsignedTemplateHelper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/BailDocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedGrantedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedMindedRefusalCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedRefusalCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailDecisionUnsignedGrantedTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailDecisionUnsignedMindedRefusalTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailDecisionUnsignedRefusalTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/BailDecisionUnsignedTemplateHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-5496
Added record decision notice unsigned document templates
```
[ ] Yes
[ x ] No
```
> Ria 5496 record the decision

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/helper/BailDecisionUnsignedTemplateHelper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/BailDecisionUnsignedTemplateHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-5496
Changes on detention location
```
[ ] Yes
[ x ] No
```
> Detention location changes

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailSubmissionCreator.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailSubmissionCreatorTest.java
https://tools.hmcts.net/jira/browse/RIA-5801
Added new make new application event
```
[ ] Yes
[ x ] No
```
> RIA-5801 added make new application event

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-5881
To address vulnerabilities
```
[ ] Yes
[X` ] No
```
> to address vulnerabilities

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/PriorApplication.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/PriorApplicationTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-5885
Added show previous application section condition
```
[ ] Yes
[ x ] No
```
> RIA-5885 Added show previous application section condition

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailDecisionUnsignedGrantedTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailDecisionUnsignedGrantedTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
[RIA-5905](https://tools.hmcts.net/jira/browse/RIA-5905)
- Update field names to reflect changes in ia-bail-case-api
**Fields affected:**
applicantMobileNumber
financialCondAmount
supporterTelephoneNumber
supporterMobileNumber
supporterEmailAddress
financialAmountSupporterUndertakes
supporter2TelephoneNumber
supporter2MobileNumber
supporter2EmailAddress
financialAmountSupporter2Undertakes
supporter3TelephoneNumber
supporter3MobileNumber
supporter3EmailAddress
financialAmountSupporter3Undertakes
supporter4TelephoneNumber
supporter4MobileNumber
supporter4EmailAddress
financialAmountSupporter4Undertakes
```
[ ] Yes
[x] No
```
> RIA-5905 Update field names

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/EndAppealAutomaticallyTemplate.java
https://tools.hmcts.net/jira/browse/RIA-5778
HMCTS logo image was missing in the document from QA testing. Added this in now and is showing locally.
```
[ ] Yes
[X] No
```
> RIA-5778 Adding in missing image field to doc

- build.gradle
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumAppealType.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumAppealTypeTest.java
- [RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- [RIA-5895](https://tools.hmcts.net/jira/browse/RIA-5895)
- [RIA-5586](https://tools.hmcts.net/jira/browse/RIA-5586)
- [RIA-6163](https://tools.hmcts.net/jira/browse/RIA-6163)
- Added EU ("EU Settlement Scheme" to AppealType enum)
```
[ ] Yes
[x] No
```
> RIA-5587 Add EU appealType

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionType.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryDecisionTypeTest.java
https://tools.hmcts.net/jira/browse/RIA-5895
Added new decision type “A decision to refuse a permit to enter the UK or entry clearance under the immigration rules and/or the EU Settlement Scheme.”
```
[ ] Yes
[x ] No
```
> Added new out-of-country type

- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6121
This is to allow any home office user with home office bails to process bails events
```
[ ] Yes
[ x ] No
```
> RIA-6121 Change HO permission roles for bail events v2

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedGrantedCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedMindedRefusalCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedRefusalCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/UploadSignedDecisionNoticeHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/bail/UploadSignedDecisionOrchestrator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/bail/UploadSignedDecisionPdfService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedGrantedCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedMindedRefusalCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedRefusalCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/UploadSignedDecisionNoticeHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/UploadSignedDecisionOrchestratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/UploadSignedDecisionPdfServiceTest.java
Merge bails record decision changes to master
Merge bails record decision changes to master
Merge bails record decision changes to master
```
[ ] Yes
[X ] No
```
> Merge bails record decision changes to master

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentre.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-6455
Added Yarl's Wood location
```
[ ] Yes
[ x] No
```
> Added Location

- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6491
```
[ ] Yes
[x] No
```
> RIA-6491: Give admin officer access to edit appeal post submission

- src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/RIA-6495
Added Yarls Wood details as a hearing centre and its address
```
[ ] Yes
[ X] No
```
> Added Yarls Wood as hearing centre and also its address

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-6424
Added some defs to AsylumCaseDefinitions to extract asylum case data
Added some putters to place case data in field values which docmosis can use in order to generate the appeal submission summary
```
[ ] Yes
[X] No
```
> Ria 6424 appeal submission summary

- .github/CODEOWNERS
- .github/renovate.json
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPO-12024
Configure renovate to update helm chart dependencies
Add codeowners
```
[ ] Yes
[x] No
```
> DTSPO-12024 - Configure renovate

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-6685
Added conditional logic to display date decision letter received / sent.
```
[ ] Yes
[x] No
```
> Ria 6685 date decision letter

- Jenkinsfile_CNP
- build.gradle
- charts/ia-case-documents-api/Chart.yaml
To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[ X] No
```
> To upgrade java chart version

- charts/ia-case-documents-api/Chart.yaml
To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```
> To revise chart version

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/State.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/StateTest.java
https://tools.hmcts.net/jira/browse/RIA-6694
Allow admin to access the submitAppeal event. 
```
[ ] Yes
[x ] No
```
> RIA-6694-Admin-Submit-Appeal

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6700
RIA-6700 - Allowing access to editAppeal for Admin users
```
[ ] Yes
[x] No
```
> RIA-6700 - Allowing access to editAppeal for Admin users

- config/owasp/suppressions.xml
To suppress new CVEs for doc store release
To suppress new CVEs for doc store release
```
[ ] Yes
[X ] No
```
> To suppress new CVEs for doc store release

- config/owasp/suppressions.xml
Reverts hmcts/ia-case-documents-api#557
> Revert "To suppress new CVEs for doc store release"

- config/owasp/suppressions.xml
Suppress CVE-2023-20863
```
[ ] Yes
[x] No
```
> RIA-6560 - Suppress CVE-2023-20863

- config/owasp/suppressions.xml
Supressed CVE-2023-28709
```
[ ] Yes
[x] No
```
> Supressed CVE-2023-28709

- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinderTest.java
> Added new line character to kick off new build on pipeline

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/Parties.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/PartiesTest.java
This is to merge non-direction changes to master
This is to merge non-direction changes to master
```
[ ] Yes
[X ] No
```
> AIP NON-DIRECTION -> Master

- config/owasp/suppressions.xml
> Added suppression to make CI/CD pipeline pass

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7158
* Formatted date
```
[ ] Yes
[X] No
```
> RIA-7158 date formatting

- config/owasp/suppressions.xml
- src/functionalTest/resources/templates/minimal-aip-appeal-submitted.json
- src/functionalTest/resources/templates/minimal-appeal-submitted.json
Updated test usernames
```
[ ] Yes
[x] No
```
> Fix functional tests

- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-judge-reheard.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-judge.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-tcw-reheard.json
- src/functionalTest/resources/scenarios/RIA-3721-update-hearing-requirements-document-tcw.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-in-country-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-in-country.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-ooc-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-submit-giving-evidence-ooc.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-in-country-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-in-country.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-ooc-reheard.json
- src/functionalTest/resources/scenarios/RIA-3825-hearing-requirements-update-giving-evidence-ooc.json
- src/functionalTest/resources/scenarios/RIA-5778-end-appeal-automatically-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/WitnessDetails.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/WitnessDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7416
```
[ ] Yes
[x] No
```
> RIA-7416 Split witness names to capture first and last names in LR journey

- src/functionalTest/resources/scenarios/RIA-7172-ho-review-evidence-letter-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/HoReviewEvidenceLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/HoReviewEvidenceLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/HoReviewEvidenceLetterTemplateTest.java
- add the new letter in the notification_letter collection.
- new tag added.
```
[ ] Yes
[x] No
```
> RIA-7172: Generate letter when 'HO Request Review' event is triggered

- src/functionalTest/resources/scenarios/RIA-7212-internal-ada-send-decision-and-reasons-allowed-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaDecisionsAndReasonsLetterAllowedGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaDecisionsAndReasonsAllowedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaDecisionsAndReasonsAllowedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaDecisionsAndReasonsLetterAllowedGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-7212
- New template for DET notification letter document attachment
- New generator and configuration bean created
- New document tag
- Added to ignore in bundle order
- Unit and functional tests
```
[ ] Yes
[X] No
```
> RIA-7212 Internal ADA Appeal decided, allowed document generation

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewSuitableLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/HoReviewEvidenceLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaDecisionsAndReasonsAllowedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/CustomerServicesProvider.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewSuitableLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaSuitabilityReviewUnsuitableLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/CustomerServicesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7540
Updated customer service provider to return internal case dynamic email/tel
```
[ ] Yes
[ x ] No
```
> Ria 7540 dynamic internal email/tel

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewSuitableLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewSuitableLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7174
- Refactor of package (template/letter)
```
[ ] Yes
[X] No
```
> RIA-7174 Refactor package location

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewUnsuitableLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewUnsuitableLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7175
- Refactor of package (template/letter)
```
[ ] Yes
[X] No
```
> RIA-7175 Refactor of package

- src/functionalTest/resources/scenarios/RIA-7200-internal-ada-hearing-bundle-ready-letter-generation.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/State.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalAdaHearingBundleReadyHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaGenerateHearingBundleTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/StateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaRequestBuildCaseDocumentGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalAdaHearingBundleReadyHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaGenerateHearingBundleTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7200
* Added generate hearing bundle doc generation for internal ADA cases
* Added unit/functional tests
```
[ ] Yes
[X] No
```
> RIA-7200 Internal ADA hearing bundle ready letter generation

- src/functionalTest/resources/scenarios/RIA-7174-internal-ada-suitability-suitable-document.json
- src/functionalTest/resources/scenarios/RIA-7175-internal-ada-suitability-unsuitable-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewSuitableLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAdaSuitabilityReviewSuitableLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7174
- added new vars to template class + unit test
```
[ ] Yes
[X] No
```
> RIA-7174 Adding new template vars to template

- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetGenerateHearingBundleTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7606
Fixed typo for AiP ADA internal cases management the dynamic email address 
```
[ ] Yes
[ x] No
```
> RIA-7606_change_customer_service_mail

- src/functionalTest/resources/scenarios/RIA-7158-request-case-building-internal-legal-officer.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalRequestBuildCaseDocumentGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalDetainedRequestBuildCaseTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalAdaRequestBuildCaseDocumentGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/InternalRequestBuildCaseDocumentGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalAdaRequestBuildCaseTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7159
- Document generation for Detained Non-ADA Request case building letter for DET
```
[ ] Yes
[X] No
```
> RIA-7159 Request case building detained letter generation

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalDetainedRequestBuildCaseTemplate.java
https://tools.hmcts.net/jira/browse/RIA-7159
- Used common method for personalisation in template to reduce duplicate lines
```
[ ] Yes
[X] No
```
> RIA-7159 Rework of Non-ADA template to reduce duplication

- build.gradle
- config/owasp/suppressions.xml
RIA-7722
Upgrade libraries to solve vulnerabilities
```
[ ] Yes
[x] No
```
> RIA-7722 Solve suppressions

- src/functionalTest/resources/scenarios/RIA-7581-internal-detained-non-ada-mark-as-paid-document-no-remission.json
- src/functionalTest/resources/scenarios/RIA-7581-internal-detained-non-ada-mark-as-paid-document-with-remission.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetMarkAsPaidLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetMarkAsPaidLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetMarkAsPaidLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedNoRemissionPaymentDueLetterTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetMarkAsPaidLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-7581
Added Internal detained Mark Appeal Paid letter
```
[ ] Yes
[ x ] No
```
> RIA-7581 Added internal detained mark as paid letter

- src/functionalTest/resources/scenarios/RIA-7580-internal-detained-non-ada-submit-appeal-appeal-fee-due-letter-generation.json
- src/functionalTest/resources/scenarios/RIA-7618-internal-detained-non-ada-remission-decision-appeal-fee-due-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/RemissionDecision.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedAppealFeeDueLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAppealFeeDueTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/RemissionDecisionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedNoRemissionPaymentDueLetterTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAppealFeeDueTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-7618
- Rebase, refactor and rename classes to be generic so they could be reused for both scenarios: SubmitAppeal with no remission + RecordRemissionDecision partially approved/rejected
- Unit tests and functional tests refactored and new one added for RecordRemissionDecision scenario
```
[ ] Yes
[X] No
```
> RIA-7618 document remission partially approved rejected

- src/functionalTest/resources/scenarios/RIA-7559-internal-detained-non-ada-list-case-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedListCaseLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedListCaseLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedListCaseLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedListCaseLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7559
- Document generation for List Case for internal detained non-Ada cases
```
[ ] Yes
[X] No
```
> RIA-7559 DET letter case listing detained

- src/functionalTest/resources/scenarios/RIA-7556-internal-detained-review-home-office-response-decision-maintained.json
- src/functionalTest/resources/scenarios/RIA-7557-internal-detained-review-home-office-response-decision-withdrawn.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedReviewHomeOfficeResponseDecisionMaintainedLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedReviewHomeOfficeResponseDecisionWithdrawnLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedReviewHomeOfficeResponseDecisionMaintainedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedReviewHomeOfficeResponseDecisionWithdrawnLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedReviewHomeOfficeResponseDecisionMaintainedLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedReviewHomeOfficeResponseDecisionWithdrawnLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedReviewHomeOfficeResponseDecisionMaintainedLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedReviewHomeOfficeResponseDecisionWithdrawnLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7557
Internal detained review HO response decision withdrawn letter generation
Note - Some changes were made to RIA-7556 (review HO response decision maintained) as the document tag was implemented incorrectly, and some refactoring to make it consistent with this PR.
```
[ ] Yes
[X] No
```
> RIA-7557 Internal detained review HO response decision withdrawn letter generation

- src/main/resources/application.yaml
> RIA-7561 - Allow LF for Request Hearing Requirements Feature

- src/functionalTest/resources/scenarios/RIA-7281-edit-case-listing-internal-detained-ada-iac-newcastle.json
- src/functionalTest/resources/scenarios/RIA-7281-edit-case-listing-internal-detained-non-ada-iac-glasgow.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedEditCaseListingDocumentGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedEditCaseListingLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedEditCaseListingDocumentGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedEditCaseListingLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7281
Added internal detained edit case listing letter
```
[ ] Yes
[ x ] No
```
> RIA-7281 Added internal detained edit case listing letter

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAndAdaDecideAnApplicationDecisionGrantedLetterTemplateTest.java
* Added isPresent() check
* Updated assertion for default case in enhanced switch statement
```
[ ] Yes
[X] No
```
> RIA-7364 Made some changes for sonar cloud failures

- charts/ia-case-documents-api/Chart.yaml
- charts/ia-case-documents-api/values.yaml
https://tools.hmcts.net/jira/browse/RIA-7802
RIA-7802 To fix incorrect env value for PROD
```
[ ] Yes
[ X] No
```
> RIA-7802 To fix incorrect env value for PROD

- src/functionalTest/resources/scenarios/RIA-7326-internal-ada-apply-for-ftpa-appellant-letter.json
- src/functionalTest/resources/scenarios/RIA-7326-internal-detained-apply-for-ftpa-appellant-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalApplyForFtpaAppellantLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalApplyForFtpaAppellantLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalApplyForFtpaAppellantLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalApplyForFtpaAppellantLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7326
internal fpa submitted letter generation
```
[ ] Yes
[X] No
```
> RIA-7326 internal fpa submitted letter generation

- src/functionalTest/resources/scenarios/RIA-7326-internal-ada-apply-for-ftpa-appellant-letter.json
- src/functionalTest/resources/scenarios/RIA-7326-internal-detained-apply-for-ftpa-appellant-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalApplyForFtpaAppellantLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalApplyForFtpaAppellantLetterGeneratorTest.java
https://tools.hmcts.net/jira/browse/RIA-7326
Updated doc tag
```
[ ] Yes
[X] No
```
> RIA-7326 Updated doc tag

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7326
* Give LR permission for applyForFTPAAppellant event doc generation
```
[ ] Yes
[X] No
```
> RIA-7326 Give LR permission for applyForFTPAAppellant event doc generation

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/WitnessDetails.java
https://tools.hmcts.net/jira/browse/RIA-7750
- Party ID generation for appellant, legal rep, witness and sponsor by using JAVA UUID
- Party ID generation involve the startAppeal, editAppeal and draftHearingRequirements event
```
[ ] Yes
[ ] No
```
> RIA-7750 party ID generation LR journey

- src/functionalTest/resources/scenarios/RIA-7331-internal-appellant-ftpa-decided-partially-granted.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalFtpaDecidedLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAppellantFtpaDecidedPartiallyGrantedTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalFtpaDecidedLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAppellantFtpaDecidedPartiallyGrantedTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7331
- New template for partially granted scenario (Appellant FTPA decided)
- Generator logic updated
```
[ ] Yes
[X] No
```
> RIA-7331 Internal appellant ftpa decided - partially granted document

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-7386
Removed suppression of CVE-2023-41080, added dependency for it with specific version without vulnerability
```
[ ] Yes
[X] No
```
> RIA-5679 Changed suppression to fixed dependency

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDecideAnApplicationDecisionGrantedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7844
* Adding full stop to String
```
[ ] Yes
[X] No
```
> RIA-7844 Add full stop to String

- src/functionalTest/resources/scenarios/RIA-7322-internal-hearing-requirements-updated-ada-letter.json
- src/functionalTest/resources/scenarios/RIA-7322-internal-hearing-requirements-updated-non-ada-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalHearingRequirementsUpdatedLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHearingRequirementsUpdatedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalHearingRequirementsUpdatedLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalHearingRequirementsUpdatedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7322
- Document generation for event: 'Update hearing requirements' for both ADA and non-ADA scenarios
- New unit and functional tests
```
[ ] Yes
[X] No
```
> RIA-7322 Internal hearing requirements updated letter generation

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
RIA 7875 - updates to resolve conflicts
RIA 7875 - updates to resolve conflicts
```
[ ] Yes
[X ] No
```
> RIA-7875  updates to resolve conflicts

- src/functionalTest/resources/scenarios/RIA-7437_Internal_Non_Standard_Direction_Letter-Nonada.json
- src/functionalTest/resources/scenarios/RIA-7437_Internal_Non_Standard_Direction_Letter-ada.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalNonStandardDirectionLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalNonStandardDirectionLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalNonStandardDirectionLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalNonStandardDirectionLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7437
Non standard direction to appellant - ADA & NonADA (Letter)
```
[ ] Yes
[ x] No
```
> RIA-7437 internal non standard direction letter

- src/functionalTest/resources/scenarios/RIA-7418-internal-edit-ada-appeal-notice-document.json
- src/functionalTest/resources/scenarios/RIA-7418-internal-edit-non-ada-appeal-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEditAppealGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEditAppealLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEditAppealGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEditAppealLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7418
Added new detained edit appeal template letter and logic behind
> RIA-7418 Appeal edited - ADA & Non ADA (Letter)

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7370
* Provide home office apc permission for uploadAdditionalEvidenceHomeOffice and uploadAddendumEvidenceHomeOffice
> RIA-7370 Provide home office apc permission for uploadAdditionalEvidenceHomeOffice and uploadAddendumEvidenceHomeOffice

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUploadAdditionalEvidenceGenerator.java
https://tools.hmcts.net/jira/browse/RIA-7370
* Added a null check on addendum metadata
> RIA-7370 Added a null check when reading addendum metadata

- config/owasp/suppressions.xml
> RIA-7370 Suppress CVE

- src/functionalTest/resources/scenarios/RIA-7471-change-direction-due-date-letter-generation-ada-internal.json
- src/functionalTest/resources/scenarios/RIA-7471-change-direction-due-date-letter-generation-non-ada-internal.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalChangeDirectionDueDateLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalChangeDirectionDueDateLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedChangeDueDateDocumentGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
> RIA-7471 letter generation direction due date changed

- src/functionalTest/resources/scenarios/RIA-7435_home_office_non_standard_direction_letter_ada.json
- src/functionalTest/resources/scenarios/RIA-7435_home_office_non_standard_direction_letter_nonada.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/HomeOfficeNonStandardDirectionLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/HomeOfficeNonStandardDirectionLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/HomeOfficeNonStandardDirectionLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/HomeOfficeNonStandardDirectionLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7435
Non-Standard direction to Home office letter
> RIA-7435 Home office non-Standard direction letter

- .github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updated Renovate scheduling
> DIAC-2 updating renovate schedule

- .github/workflows/swagger.yml
> RIA-1234 swagger workflow run fix

- src/functionalTest/resources/scenarios/RIA-7429-internal-reinstate-appeal-document-ada.json
- src/functionalTest/resources/scenarios/RIA-7429-internal-reinstate-appeal-document-non-ada.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalReinstateAppealLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalReinstateAppealLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalReinstateAppealLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalReinstateAppealLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7429
- Document generation for Internal Reinstate appeal: ADA and non-ADA scenarios
- Unit and functional tests
> RIA-7429 Letter generation for Internal Reinstate Appeal

- src/functionalTest/resources/scenarios/RIA-7435_appellant_respondent_non_standard_direction_letter_ada.json
- src/functionalTest/resources/scenarios/RIA-7435_home_office_non_standard_direction_letter_ada.json
- src/functionalTest/resources/scenarios/RIA-7435_home_office_non_standard_direction_letter_nonada.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalNonStandardDirectionLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalNonStandardDirectionToRespondentLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalNonStandardDirectionToRespondentLetterGeneratorTest.java
> RIA-7435 Rename the letter generator class and corresponding unit tests

- .github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updating config option, old option deprecated
> DIAC-2 changing deprecated config option

- .github/workflows/pr-title-validation.yml
- build.gradle
> DIAC-000 Dependency fix

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7537
Additional role access being given to Legal officer for EJP cases
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] Does this PR introduce a breaking change
> RIA-7537 EJP LO additional events

- charts/ia-case-documents-api/Chart.yaml
- config/owasp/suppressions.xml
> RIA-8888 Upgraded chart version

- config/owasp/suppressions.xml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7882
RIA-7882 Add editCaseListing permission for caseworker-ia-system
> RIA-7882 Add editCaseListing permission for caseworker-ia-system

- .github/workflows/pr-title-validation.yml
- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- charts/ia-case-documents-api/Chart.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/util/AuthorizationHeadersProvider.java
- src/functionalTest/resources/scenarios/RIA-5778-end-appeal-automatically-notice-document.json
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/GenerateDecisionAndReasonsTestWiremock.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/GivensBuilder.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/IaCaseDocumentsApiClient.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/SpringBootIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/component/testutils/WithStitchingStub.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/StitchingApiHttpErrorsTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/utilities/AsylumCaseFixtures.java
https://tools.hmcts.net/jira/browse/DIAC-66
> DIAC-66 getting all functionals to run

- build.gradle
- charts/ia-case-documents-api/Chart.yaml
- config/owasp/suppressions.xml
N/A
Revert pact dependency upgrade to fix local build.
> DIAC-00 Revert pact dependency upgrade

- build.gradle
RIA-TASK - Removed print line that causes issues on windows
> RIA-TASK - Removed print line that causes issues on windows

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
- src/functionalTest/resources/scenarios/bail/RIA-5218-bail-end-application-document.json
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-granted.json
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-judge-minded-refusal.json
- src/functionalTest/resources/scenarios/bail/RIA-5496-bail-decision-notice-unsigned-document-refusal.json
- src/functionalTest/resources/scenarios/bail/RIA-5610-bail-application-submission-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7973
Updated Bail application details template
> RIA-7973 Updated Bail application details template

- config/owasp/suppressions.xml
> DIAC-123 suppressions update 04/12/23

- src/functionalTest/resources/scenarios/RIA-7324-adjourn-hearing-without-date-internal-detained-ada.json
- src/functionalTest/resources/scenarios/RIA-7324-adjourn-hearing-without-date-internal-detained-non-ada.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedAdjournHearingWithoutDateLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAdjournHearingWithoutDateLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedAdjournHearingWithoutDateLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAdjournHearingWithoutDateLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-7324
Added hearing adjourned without a date template letter changes
> RIA-7324 Hearing adjourned without a date - ADA & Non ADA (Letter)

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8364
- Updated bail application template from 01134 to 01144.docx
> RIA-8364 Bail template change 01134 -> 01144

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/DIAC-110
> DIAC-110 turning on fortify

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8214
bail application submission template fixed with new fields
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
> RIA-8214 Add a new screen to Bails start application - UT appeal pending

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
Reverts hmcts/ia-case-documents-api#791
> Revert "RIA-8214 Add a new screen to Bails start application - UT appeal pending"

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/InterpreterLanguageRefData.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8489
Refactored interpreter language
> RIA-8489 Refactored interpreter language

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/bail/BailInterpreterLanguageRefData.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingRequirementsTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8508
Fix appeals refactored interpreter language
> RIA-8508 Fix appeals refactored interpreter language

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/bail/BailDecisionUnsignedRefusalCreator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/BailDecisionUnsignedRefusalCreatorTest.java
https://tools.hmcts.net/jira/browse/RIA-8212
updated refused decision template under IMA status
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
> RIA-8212 Decision refused under IMA - Decision template

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/BailSubmissionTemplateTest.java
Tests coverage for Sonar cloud
> RIA-1111 sonar_fix 

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingInitialListingTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingRelistingTemplateTest.java
> RIA-8554 Fix detention location on hearing-notice template

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingTemplate.java
> RIA-8554 Using enums for Field definition comparison

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatus.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatusTest.java
https://tools.hmcts.net/jira/browse/DIAC-195
revert change due to potential failings in em (504 gateway errors)
> DIAC-195 - revert enum change

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7957
- Added event authorisation 'uploadHomeOfficeAppealResponse' to respondent user
> RIA-7957 Adding event authorisation for Upload Appeal Response for respondent user

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/DIAC-236
> DIAC-236 splitting up tests to separate stages

- src/functionalTest/resources/scenarios/RIA-8721-update-tribunal-decision-cover-letter-aip.json
- src/functionalTest/resources/scenarios/RIA-8721-update-tribunal-decision-cover-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpdateTribunalDecisionCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpdateTribunalDecisionCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8211
- introduce new document tag "updatedDecisionAndReasonsCoverLetter"
- update unit test and functional test
> RIA-8211 update tribunal decision rule 31 aip timeline

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalAipDecisionAndReasonsCoverLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalDecisionAndReasonsCoverLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateHelper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalAipDecisionAndReasonsCoverLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-8211
- fix the [sonarCloud problem](https://sonarcloud.io/component_measures?metric=new_duplicated_blocks&view=list&pullRequest=808&id=IACASEDOCUMENTSAPI) to unblock the ticket 8211
- update the unit test
> RIA-8211 fix the code smell problem of sonarCloud

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8738
> RIA-8738 IMA - Rebasing docmosis template

- src/functionalTest/resources/scenarios/RIA-8721-update-tribunal-decision-cover-letter-aip.json
- src/functionalTest/resources/scenarios/RIA-8721-update-tribunal-decision-cover-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DecisionAndReasons.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpdateTribunalDecisionCreator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DecisionAndReasonsTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/UpdateTribunalDecisionCreatorTest.java
https://tools.hmcts.net/jira/browse/RIA-8239
Added unit tests and updated functional tests
> RIA-8239 Added unit tests and updated functional tests

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
https://tools.hmcts.net/jira/browse/DIAC-281
> DIAC-281 fixing CcdScenarioRunnerTest

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalDecisionAndReasonsCoverLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateHelper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/helper/UpdatedTribunalDecisionAndReasonsCoverLetterTemplateHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-8721
Fixed HMCTS logo for AIP cover letter AMENDED
> RIA-8721 Fixed HMCTS logo for AIP cover letter AMENDED

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8210
Update tribunal decision Rule31- Documents tab post event
> RIA-8210 update tribunal decision docuement tab r31

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
> RIA-0000 Fix issues in functional tests

- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
https://tools.hmcts net/jira/browse/RIA-8758
Fix func tests patch
> RIA-8758 fix func tests patch

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iacasedocumentsapi/CcdScenarioRunnerTest.java
[RIA-8774](https://tools.hmcts.net/jira/browse/RIA-8774)
- Functional tests run in AAT
```
[ ] Yes
[x] No
```
> RIA-8774 Add logging

- src/functionalTest/resources/scenarios/RIA-8772-reheard-listing-hearing-noticed-remitted.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ReheardHearingDocuments.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ReheardHearingDocumentsTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/AsylumPreSubmitCallbackDispatcherTest.java
https://tools.hmcts.net/jira/browse/RIA-8772
Added remitted reheard document complex collections
> RIA-8772 Added remitted reheard document complex collections

- config/owasp/suppressions.xml
> RIA-8888 update suppressions.xml

- src/functionalTest/resources/scenarios/RIA-7212-internal-ada-send-decision-and-reasons-allowed-document.json
- src/functionalTest/resources/scenarios/RIA-7213-internal-ada-send-decision-and-reasons-dismissed-document.json
- src/functionalTest/resources/scenarios/RIA-7215-internal-detained-non-ada-send-decision-and-reasons-allowed-document.json
- src/functionalTest/resources/scenarios/RIA-7216-internal-detained-non-ada-send-decision-and-reasons-dismissed-document.json
> RIA-TASK - Fix failed functional tests

- src/functionalTest/resources/scenarios/RIA-8256-ftpa-reheard-decisions-and-reasons-complex-collection.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestrator.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/SendDecisionAndReasonsOrchestratorTest.java
https://tools.hmcts.net/jira/browse/RIA-8256
Added reheard decision complex collection
> RIA-8256 reheard decision complex collection

- src/functionalTest/resources/scenarios/RIA-8291-generate-hearing-bundle-remitted.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/RemittalDocument.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AdvancedBundlingCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8291
Added new bundle config for Remitted case
> RIA-8291 Added new bundle config for Remitted case

- src/main/resources/application.yaml
RIA-8852 : To provide permission for async stitching event for admin and judge user types
RIA-8852 : To provide permission for async stitching event for admin and judge user types
> RIA-8852 To provide permission for async stitching event for admin and judge user types

- Jenkinsfile_nightly
Fixed nightly test configuration
> RIA-TASK - Fixed nightly test configuration

- src/main/resources/application.yaml
RIA-000 Update to fix the perm issue for system user
RIA-000 Update to fix the perm issue for system user
> RIA-000 Update to fix the perm issue for system user

- src/main/resources/application.yaml
RIA-TASK - Update permissions for event
> RIA-TASK - Update permissions for event 

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8900
Update permissions for event
> RIA-TASK - Update permissions for event

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/model/refdata/CourtVenue.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/BailCaseFieldDefinitionTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingInitialListingTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/bail/BailNoticeOfHearingRelistingTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8802
- display the listing location from ref data instead of using CCD address
- update unit test
> RIA-8802 bails notice of hearing displays the correct location information

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/controllers/advice/CallbackControllerAdvice.java
https://tools.hmcts.net/jira/browse/RIA-8935
> RIA-8935 Fix issue in Exception management

- src/main/resources/application.yaml
RIA-8913 Updates to enable bail HO events for HO POU users
RIA-8913 Updates to enable bail HO events for HO POU users
> RIA-8913 Updates to enable bail HO events for HO POU users

- src/functionalTest/resources/scenarios/RIA-8256-ftpa-reheard-decisions-and-reasons-complex-collection.json
- src/functionalTest/resources/scenarios/RIA-8772-reheard-listing-hearing-noticed-remitted.json
REMITTED functional test disabled
> RIA-8663 REMITTED functional test disabled -> Master: 

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8839
> RIA-8839 Refactor the handling of 'decisionWithoutHearing' appeals

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8931
Added supporting documents save to Legal rep category.
> RIA-8931 add_supporting_documents

- build.gradle
> DIAC-123 dropping mutation threshold to 85

- src/functionalTest/resources/scenarios/RIA-8305-internal-non-detained-case-listed-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/DateTimeExtractor.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8305
Case listed - Non Detained (by post) notification
> RIA-8305 case listed non detained letter

- src/functionalTest/resources/scenarios/RIA-2970-hearing-adjourned-notice-document-iac.json
- src/functionalTest/resources/scenarios/RIA-8331-internal-non-detained-case-adjourned-without-date-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
https://tools.hmcts.net/jira/browse/RIA-8331
Added document and bundle generations for "Hearing adjourned without a date - Non Detained & OOC (by post) notification"
> RIA-8331 RIA-8331 adjourned_without_a_date

- src/functionalTest/resources/scenarios/RIA-9172-internal-non-detained-end-appeal-letter-ooc.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEndAppealLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEndAppealLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9172
- Adding check for APPELLANT_HAS_FIXED_ADDRESS_ADMIN_J
- Reading address from Internal OOC fields separate from Appellant Address in-country flow
> RIA-9172 OOC changes for internal end appeal letter+bundle generation

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandler.java
https://tools.hmcts.net/jira/browse/RIA-9172
- Moved line to reduce code duplication % in sonar check
> RIA-9172 Addressing sonar line duplication %

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-9172
- To unblock sonar from duplications
> RIA-9172 remove duplications into utils method

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseListedLetterHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
https://tools.hmcts.net/jira/browse/RIA-9172
To unblock sonar from duplications
> RIA-9172 remove duplications

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatus.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/field/PaymentStatusTest.java
Reverts hmcts/ia-case-documents-api#827
> DIAC-195 - reintroduce enum change"

- .github/workflows/stale.yml
> DIAC-507 - DTSSE-5078 - Add stalebot

- src/functionalTest/resources/scenarios/RIA-8331-internal-non-detained-case-adjourned-without-date-letter-oot.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8331
Fixed logic for OOT cases, FT and junits
>  RIA-8331 fix_for_oot_cases

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalCaseAdjournedWithoutTimeLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-8331
Change hearing location address in the template to Hearing center name
> RIA-8331 hearing_center_name

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryCircumstances.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/OutOfCountryCircumstancesTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
https://tools.hmcts.net/jira/browse/RIA-9207
RIA-9207 Update AppealSubmission with out of country circumstances
> RIA-9207 Update AppealSubmission with out of country circumstances

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-9130
RIA-9130 Make Update Tribunal decision event available to LO
> RIA-9130 Make Update Tribunal decision event available to LO

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/CdamDocumentDownloadClient.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/CdamDocumentManagementUploader.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DmDocumentDownloadClient.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DmDocumentManagementUploader.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocumentDownloadClient.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocumentManagementUploader.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/clients/DocumentManagementUploaderTest.java
DIAC-555
https://tools.hmcts.net/jira/browse/DIAC-555
> DIAC-555 add logs

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DecisionAndReasonsTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/HearingDetailsFinder.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/DecisionAndReasonsTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9437
Fix for missing listCaseHearingCentre error when submitting Prepare decision and reasons event
- [x ] commit messages are meaningful and follow good commit message guidelines
> RIA-9437 - Fix for missing listCaseHearingCentre error when submitting Prepare decision and reasons event

- src/functionalTest/resources/scenarios/RIA-8224-update-tribunal-decision-rule31-document.json
- src/functionalTest/resources/scenarios/RIA-82240-update-tribunal-decision-rule32-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUpdateTribunalDecisionR31Generator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUpdateTribunalDecisionR32Generator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalUpdateTribunalDecisionR31Template.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalUpdateTribunalDecisionR32Template.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUpdateTribunalDecisionR31GeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalUpdateTribunalDecisionR32GeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalUpdateTribunalDecisionR31TemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalUpdateTribunalDecisionR32TemplateTest.java
Jira link
https://tools.hmcts.net/jira/browse/RIA-8224
Change description
Update Tribunal decision - Detained Non ADA notification
> RIA-8224 Update Tribunal decision - Detained Non ADA notification

- src/functionalTest/resources/scenarios/RIA-3132-ftpa-reheard-send-decisions-and-reasons.json
- src/functionalTest/resources/scenarios/RIA-3683-reheard-hearing-notice-document-iac-birmingham.json
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-stitching-save-and-return-disabled.json
- src/functionalTest/resources/scenarios/RIA-481-appeal-skeleton-document-stitching-save-and-return-enabled.json
- src/functionalTest/resources/scenarios/RIA-5778-end-appeal-automatically-notice-document.json
- src/functionalTest/resources/scenarios/RIA-8256-ftpa-reheard-decisions-and-reasons-complex-collection.json
- src/functionalTest/resources/scenarios/RIA-8772-reheard-listing-hearing-noticed-remitted.json
See [RIA-9261](https://tools.hmcts.net/jira/browse/RIA-9261)
Review the below PRs, identify the FTs that are disabled in the PR and see it can be enabled now. 
 https://github.com/hmcts/ia-hearings-api/pull/386
https://github.com/hmcts/ia-case-notifications-api/pull/907
https://github.com/hmcts/ia-case-documents-api/pull/609
https://github.com/hmcts/ia-home-office-integration-api/pull/344
https://github.com/hmcts/ia-case-api/pull/1497
https://github.com/hmcts/ia-aip-frontend/pull/972
Review the WA FT repo and merge the ILA FT changes to master branch.
https://github.com/hmcts/ia-task-configuration/pull/377
> RIA-9261 - Enable ILA FTs for Pipeline

- src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/RIA-9472
Added 2 new countries
> RIA-9472 Added 2 new countries

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/AppealSubmissionDocFieldMapper.java
> RIA-TASK Fix sonnar issues

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/AppealSubmissionDocFieldMapper.java
Fix Sonar scan issue out of country circumstances field
> RIA-TASK Fix Sonar scan issue out of country circumstances field

- charts/ia-case-documents-api/Chart.yaml
- infrastructure/state.tf
Upgrade java helm chart and terraform version
> DIAC-000 Upgrade java helm chart

- build.gradle
> DIAC-000 - potential mutation test fix

- build.gradle
> DIAC-000 - fix pitest mutation tests

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/AppealSubmissionDocFieldMapper.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/AppealSubmissionTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/InternalOocAppealSubmissionTemplateTest.java
See [DIAC-1029](https://tools.hmcts.net/jira/browse/DIAC-1029)
- If the appellant has provided a Custodial sentence release date (which they should be able to  via other or prison) then this release date should be displayed in the pdf summary
> DIAC-1029 Appeal Submission Summary Template ICC

- build.gradle
- config/owasp/suppressions.xml
> DIAC-688 pipeline fix

- src/functionalTest/resources/scenarios/DIAC-1369-end-appeal-detained-other-appellant-notice-document.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/EndAppealNoticeCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEndAppealLetterWithAttachmentBundleHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/DIAC-1369
> DIAC-1369 end appeal detained in other notification

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEditCaseListingLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalEditCaseListingLetterWithAttachmentBundleHandler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/DIAC-1305
Constraining condition to aip-manual when detained in other
> DIAC-1305 fixing condition

- src/functionalTest/resources/scenarios/DIAC-1298-detained-other-hearing-notice-document-iac-hatton-cross.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/DetainedCaseListedLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/DetainedCaseListedLetterHandler.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/DetainedCaseListedLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/DetainedCaseListedLetterHandlerTest.java
https://tools.hmcts.net/jira/browse/DIAC-1298
> DIAC-1298 list case detained other notification

- src/functionalTest/resources/scenarios/DIAC-1321-internal-detained-irc-submit-appeal.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionDetainedPrisonIrcCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedEditCaseListingDocumentGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalAppealSubmissionTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedPrisonIrcAppealSubmissionTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/AppealSubmissionDetainedPrisonIrcCreatorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedPrisonIrcAppealSubmissionTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/DIAC-1321
> DIAC-1321 Paper appeal submitted on time with remission request detained in irc or prison notification

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/DetainedLegalRepRemovedIrcPrisonTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/DetainedLegalRepRemovedIrcPrisonTemplateTest.java
See [DIAC-1426](https://tools.hmcts.net/jira/browse/DIAC-1426)
Fix legal rep reference number in template
> DIAC-1426 Fix legal rep reference number in template

- src/main/resources/application.yaml
DIAC-1426 updates to fix role permission for remove legal representative event
DIAC-1426 updates to fix role permission for remove legal representative event
> DIAC-1426 updates to fix role permission for remove legal representative event

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAppealRemissionPartiallyGrantedOrRefusedTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedAppealRemissionPartiallyGrantedOrRefusedTemplateTest.java
https://tools.hmcts.net/jira/browse/DIAC-1328
Fixing missing case reference number in template
> DIAC-1328 Missing case reference number

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/AsylumCaseDefinition.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEditCaseListingLetterTemplate.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEditCaseListingLetterTemplateTest.java
https://tools.hmcts.net/jira/browse/DIAC-1305
Adding hearing channel
> DIAC-1305 adding hearing channel

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTag.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedLateRemissionGrantedTemplateLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrder.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedLateRemissionGrantedTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/infrastructure/config/DocumentCreatorConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/DocumentTagTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedLateRemissionGrantedTemplateLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/BundleOrderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedLateRemissionGrantedTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
See [DIAC-1403](https://tools.hmcts.net/jira/browse/DIAC-1403)
Late remission request granted - Detained (in IRC or Prison) notification
> DIAC-1403 Late remission request granted - Detained (in IRC or Prison) notification

- src/functionalTest/resources/scenarios/DIAC-1297-detained-in-prison-non-ada-list-case-LR-letter.json
- src/functionalTest/resources/scenarios/RIA-7559-internal-detained-non-ada-list-case-letter.json
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/HearingNoticeCreator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/DetainedIrcPrisonCaseListedDocumentBundler.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedListCaseLetterGenerator.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapper.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedListCaseLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalEditCaseListingLetterTemplate.java
- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtils.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/handlers/presubmit/letter/InternalDetainedListCaseLetterGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/service/HearingNoticeFieldMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/CmaAppointmentNoticeTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/HearingNoticeUpdatedTemplateProviderTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/templates/letter/InternalDetainedListCaseLetterTemplateTest.java
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/DIAC-1297
> DIAC-1297 Case listed - Detained (in IRC or Prison) notification

- src/main/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/Event.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iacasedocumentsapi/domain/entities/ccd/EventTest.java
https://tools.hmcts.net/jira/browse/DIAC-1390
As part of the detained appeals work, there is a requirement to trigger document generation for IRC/Prison notifications when an FTPA application is decided. The purpose of this change is to add decideFTPAApplication to the documents API scope for judicial users.
> DIAC-1390 Extending permission for decideFTPAApplication
